### ISSUE TITLE
Invalid URLs in Installation docs

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#102]
<a href="https://github.com/tobias-johansson"><img src="https://avatars.githubusercontent.com/u/1613054?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tobias-johansson](https://github.com/tobias-johansson)**
_Thursday Oct 31, 2019 at 08:59 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1327_

----

Found a couple of broken URLs in the Installation docs

- https://neo4j.com/docs/labs/apoc/current/introduction/#_manual_installation_download_latest_release contains 404 url `http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.5`
- https://neo4j.com/docs/labs/apoc/current/introduction/#_using_apoc_with_the_neo4j_docker_image contains 404 url `https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5/apoc-3.5-all.jar`
- https://neo4j.com/docs/labs/apoc/current/introduction/#usage contains a broken url `https://raw.githubusercontent.com/neo4j-contrib/neo4j-apoc-procedures/{branch}/src/test/resources/person.json`

**Comment by gem-neo4j** [comment]
This is fixed in APOC core docs, and a fix is made for APOC extended, pending release :)
