### ISSUE TITLE
APOC conditional procedures don't yield results if 

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#104]
<a href="https://github.com/InverseFalcon"><img src="https://avatars.githubusercontent.com/u/8800736?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [InverseFalcon](https://github.com/InverseFalcon)**
_Wednesday Dec 04, 2019 at 23:49 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1365_

----

## Expected Behavior

When using `apoc.when()`, `apoc.do.when()`, `apoc.case()`, and `apoc.do.case()`, we would expect that we would always have a row present after the call so we can continue working in the query.

## Actual Behavior

For a non-empty query string, when RETURN isn't present in that string that end up being executed, nothing is YIELDed in the query, effectively wiping out the row and shortcircuiting any further operations.

(note that empty query strings, such as a `''` for the else part, behaves as expected...the YIELDed value is present for the row, it is just an empty map)

## How to Reproduce the Problem

Provided there as at least one node in the graph:

```
MATCH (n) 
WITH n 
LIMIT 1
CALL apoc.do.when(true, 'REMOVE n.nonExistent', '', {n:n}) YIELD value
RETURN value
```

Because the query string executed is non-empty and does not RETURN anything, nothing is YIELDed, so the row is wiped out and the query doesn't return anything. 

This seems like unexpected and unwanted behavior. We do not want this to act as a filter, if that's needed then it can be handled outside of the procedure call.

**Comment by gem-neo4j** [comment]
This is now fixable in pure [Cypher](https://neo4j.com/docs/cypher-manual/current/clauses/call/#optional-call);

Your query can now be written as:

```
MATCH (n) 
WITH n 
LIMIT 1
OPTIONAL CALL apoc.do.when(true, 'REMOVE n.nonExistent', '', {n:n}) YIELD value
RETURN value
```

Then a null value will be returned :)
