### ISSUE TITLE
apoc.export.csv.query() does not register duration.inSeconds formatting

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#121]
<a href="https://github.com/edtky"><img src="https://avatars.githubusercontent.com/u/35285568?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [edtky](https://github.com/edtky)**
_Sunday Apr 28, 2019 at 19:58 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1184_

----

## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

`CALL apoc.export.csv.query(" ... ... RETURN duration.inSeconds(a.timeStamp, b.timeStamp) ..." )`
should return "P0M0DT2651S" in the csv file (only seconds)

## Actual Behavior (Mandatory)

wrongly returns "PT44M11S" in csv file (minutes and seconds)
(when queried directly on Neo4j, it correctly returns "P0M0DT930S" on the dashboard)

### Simple Dataset (where it's possible)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Screenshots (where it's possible)

![Screen Shot 2019-04-28 at 11 31 00 AM](https://user-images.githubusercontent.com/35285568/56869415-4cccd480-69b5-11e9-88e1-a87dec7e27ef.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/vboulaye"><img src="https://avatars.githubusercontent.com/u/652767?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vboulaye](https://github.com/vboulaye)**
_Saturday Oct 05, 2019 at 11:27 GMT_

----

Hi,
I tried to work on this issue.
I managed to reproduce it (I made a test in dba589c95267db960d86c7ae41ad260a9359a96b).

But I cannot figure out how the dashboard is working: the output from csv.query is calling the `toString()` from ` DurationValuè` which is always computing an hour/minute component from the seconds in the duration.

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/enriquezrene"><img src="https://avatars.githubusercontent.com/u/1638636?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [enriquezrene](https://github.com/enriquezrene)**
_Wednesday Oct 23, 2019 at 18:15 GMT_

----

@vboulaye 
The issue is DurationValue.toString is invoking prettyPrint() which transforms seconds to hours, minutes.

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/enriquezrene"><img src="https://avatars.githubusercontent.com/u/1638636?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [enriquezrene](https://github.com/enriquezrene)**
_Wednesday Oct 23, 2019 at 18:34 GMT_

----

I think the following PR might work https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1322 
I took the changes from your commit. @vboulaye

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/fbiville"><img src="https://avatars.githubusercontent.com/u/445792?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fbiville](https://github.com/fbiville)**
_Friday Mar 05, 2021 at 17:43 GMT_

----

> I managed to reproduce it (I made a test in [dba589c](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/dba589c95267db960d86c7ae41ad260a9359a96b)).

Based on a slightly updated variant of this test, the Java API of Neo4j and Cypher-Shell return 1 value: `"PT9H5M35.353S"`.
Neo4j Browser returns another `P0M0DT32735.353000000S`.
It might be a driver issue.

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Thursday May 13, 2021 at 12:38 GMT_

----

@fbiville any news on this?

**Comment by gem-neo4j** [comment]
Hi there!

I see the confusion, as mentioned above, it is the pretty print of the duration that looks like it isn't in seconds. The actual Duration object however is still in seconds and is equivalent. What I suggest is that if you want to export seconds specifically to not use the default toString on a duration:

e.g specifically pull out the seconds:
`RETURN duration.inSeconds(datetime('2015-06-24T12:05:35.556+0100'), datetime('2015-06-24T12:50:30.556+0100')).seconds 
`

As this is not an APOC issues (will happen if you simply run in Browser: 
`RETURN toString(duration.inSeconds(datetime('2015-06-24T12:05:35.556+0100'), datetime('2015-06-24T12:50:30.556+0100')))`

I will close this, feel free to open an issue on Neo4j about the pretty print :)

Thanks, 
Gem
