### ISSUE TITLE
Export graphml, ignores types even if set to useTypes: true in config

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#132]
<a href="https://github.com/stefan-sev"><img src="https://avatars.githubusercontent.com/u/6778226?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stefan-sev](https://github.com/stefan-sev)**
_Monday Aug 21, 2017 at 12:36 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/556_

----

Given scenario:

'Create (:Test{limit: 1500000000000}), (:Test{limit: 2})'
Returns 2 nodes with the same label and the same properties, but once it is saved as int and the other time it is saved as long.

Now if I will create a dump in graphml with Types, there will be no key for limit and so for no types at all.

Here are to Code fragments causing this:

First it will set the type of limit to Long and on the second cycle it compares Long with int and sets the type to void.

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/337b2e12401c0df95e44db0922946d9f5c643115/src/main/java/apoc/export/util/MetaInformation.java#L36-L47

Type void will be ignored.

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/337b2e12401c0df95e44db0922946d9f5c643115/src/main/java/apoc/export/util/MetaInformation.java#L52

Possible solutions:

1. Aggregate types of key to the biggest type. In this example Long

Problem: What if there are two different Nodes, one node sets limit to String, the other node sets limit to Long. What type should be chosen? 

2. Additional attribute type on data level instead of key block

Every data element defines the type separately, but this could be redundant information.

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/StephanHasler"><img src="https://avatars.githubusercontent.com/u/30526523?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [StephanHasler](https://github.com/StephanHasler)**
_Friday Jan 11, 2019 at 17:14 GMT_

----

I observed this bug too.
Whenever attributes with the same name are not all of the same type, no key entry is generated for this attribute name during graphml export.

One solution might be to have a separate key id for all combinations of attr.name and attr.type.

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Thursday May 13, 2021 at 08:06 GMT_

----

fixed as highlited in #840

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Thursday May 13, 2021 at 08:11 GMT_

----

looking better it may be worth of a double check

**Comment by hvub** [comment]
cf. https://github.com/neo4j/apoc/issues/35#issuecomment-2483397148

> This behavior is due to a restriction of GraphML. GraphML assumes that all node or relationship properties with the same property name have property value of the same type. Neo4j allows mixed types per property name. If a property name has value of mixed value types, then its value are exported as a STRING.
>
> If a node property name is associated with property value of different types, e.g. as in (:LabelA {prop: 123}), (:LabelB {prop: 'abc'}) or as in the example above, then no property type information is written to the graphml output for that node property name. The same holds for relationship properties.
