### ISSUE TITLE
improve apoc.group.nodes

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#140]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Friday May 11, 2018 at 22:21 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/804_

----

return nodes individually for browser/bloom

- allow to filter relationships (with wildcards and by direction)
- add filters on counts to filter out less relevant or too dense nodes / rels
- figure out a better api
- move from parameters to config
- support projections (virtual graphs as source for grouping)
- optional computed grouping property, e.g. write cypher that returns nodes and the property to group by e.g. `match (m:Movie)-->(g:Genre) return g.name as group, m as node`
- build a visual tool on top, similar to: https://github.com/dbs-leipzig/gradoop_demo#graph-grouping
- option to remove self relationships
- option to remove orphan nodes

**Comment by nadja-muller** [comment]
This procedure doesn't seem to exist anymore. See also: https://github.com/neo4j/apoc/issues/144
