### ISSUE TITLE
The `apoc.import.json` constraint check should works only when an unique constraint exists

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#15]
<a href="https://github.com/vga91"><img src="https://avatars.githubusercontent.com/u/25103389?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vga91](https://github.com/vga91)**
_Tuesday May 24, 2022 at 10:52 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2930_

----

## Expected Behavior (Mandatory)

Missing constraint error

## Actual Behavior (Mandatory)

The import works

## How to Reproduce the Problem

Create a file `all.json` with label `User`:
```
{"type":"node","id":"0","labels":["User"],"properties":{"born":"2015-07-04T19:32:24","name":"Adam","place":{"crs":"wgs-84","latitude":33.46789,"longitude":13.1,"height":null},"male":true,"age":42,"kids":["Sam","Anna","Grace"]}}
```

Try to import the file without constraints:
```
CALL apoc.import.json('all.json')
```
this will throw an error message:
```
Missing constraint required for import. Execute this query: 
CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS UNIQUE;
```

Create an existence constraint instead of an unique one.
```
CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS NOT NULL
```

Retry the import and note that it's work.

### Versions

  - OS: OSX
  - Neo4j: 4.3.11
  - Neo4j-Apoc: 4.3.0.5

**Comment by gem-neo4j** [comment]
Thanks for reporting this :) this is fixed and should be in the next releases (5.8 and 4.4.0.16)
