### ISSUE TITLE
apoc.import.graphml issue - export using same APOC library

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#152]
<a href="https://github.com/giribabuvenugopal"><img src="https://avatars.githubusercontent.com/u/18420998?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [giribabuvenugopal](https://github.com/giribabuvenugopal)**
_Friday May 12, 2017 at 23:05 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/438_

----

i am getting following error

graphml size is 26 gb

neo4j> CALL apoc.import.graphml("/backup/ex_mus_graphml",{batchsize:10000, readLabels: true, storeNodeIds: false, defaultRelationshipType:"RELATED"});
Failed to invoke procedure `apoc.import.graphml`: Caused by: java.lang.RuntimeException: Error executing in separate thread: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[13972763,232]
Message: An invalid XML character (Unicode: 0x7) was found in the element content of the document.
neo4j>

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/giribabuvenugopal"><img src="https://avatars.githubusercontent.com/u/18420998?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [giribabuvenugopal](https://github.com/giribabuvenugopal)**
_Monday May 15, 2017 at 16:13 GMT_

----

i was when look into query line i dont see it. anything

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/WyrdNexus"><img src="https://avatars.githubusercontent.com/u/7062928?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [WyrdNexus](https://github.com/WyrdNexus)**
_Friday Aug 30, 2019 at 22:26 GMT_

----

I just encountered the exact same issue. Unicode char was in source data, which was imported using `apoc.load.json`

One node has a string property containing `"1628\u001e–30"`.

Note: tracking this down is much easier with an editor which will display unusual characters. 

In this instance, GraphML export _should not_ allow those characters through without either removing them, or encoding them. 

**Heading:** `<?xml version="1.0" encoding="UTF-8"?>` should not allow for any non-utf-8 characters, though solving that problem is no easy task.

Editing the file created by `apoc.export.graphml.all('file',{})` revealed unicode characters displayed as `<0x1e>`. 

Fixing the file:
1. Regex find and replace:
    * Find: `[\x{07}\x{1e}\x{1f}]`
    * ReplaceWith: ` `
2. Save with encoding: `UTF-8`

Following those corrective steps, the import ran cleanly. However, "just delete it," isn't generally a good option which building DB utilities. Let me know if I can help.

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/vga91"><img src="https://avatars.githubusercontent.com/u/25103389?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vga91](https://github.com/vga91)**
_Thursday Sep 23, 2021 at 10:25 GMT_

----

Related to #1283

**Comment by vga91** [comment]
Fixed by #199
