### ISSUE TITLE
go over all procedures / functions that use restricted APIs and check if we really need them

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#156]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Thursday Mar 30, 2017 at 09:05 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/353_

----

● GraphDatabaseAPI
● KernelTransaction
● DependencyResolver
● UserManager
● EnterpriseAuthManager 
● SecurityLog

replace if possible with

● Log
● TerminationGuard
● GraphDatabaseService (​This now allows creation of new Transactions in new Threads)
● SecurityContext
● ProcedureTransaction

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/inserpio"><img src="https://avatars.githubusercontent.com/u/6613815?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [inserpio](https://github.com/inserpio)**
_Thursday Apr 20, 2017 at 13:34 GMT_

----

Create a new KernelApi class encapsulting access to Kernel classes

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jexp](https://github.com/jexp)**
_Thursday Apr 20, 2017 at 13:57 GMT_

----

Aquiring:
- graph properties
- KernelTX
- Statement
- [Read/Write/TokenWrite]Operations
- TerminationGuard

Possibly move some methods from Util to KernelAPI

**Comment by nadja-muller** [comment]
Original is closed.
