### ISSUE TITLE
apoc.rename.label has wrong example (from apoc.rename.type)

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#20]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Thursday Aug 04, 2022 at 09:52 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3112_

----

 APOC refactor.rename.label contains the wrong example (the example in https://neo4j.com/labs/apoc/4.4/overview/apoc.refactor/apoc.refactor.rename.label/ is for renaming types)

/cc @michael-simons

**Comment by gem-neo4j** [comment]
Fixed on 5.x already, will be released on 4.4 next docs release :)
