### ISSUE TITLE
apoc.coll.different() returning false when it should return true

### ISSUE THREAD

**Issue by apurvis** [neo4j/apoc#227]
## Expected Behavior (Mandatory)
`RETURN apoc.coll.different([1,1,3])` should yield `true` because 3 is different from 1, and the docs describe the function as:
> _apoc.coll.different(coll [Any]) - returns true if **any** of the values in the given list are different._

The word **any** implies to me that if a single number is different, the function should return `true`.

## Actual Behavior (Mandatory)
`RETURN apoc.coll.different([1,1,3])` yields false.

## How to Reproduce the Problem
Run the query: `RETURN apoc.coll.different([1,1,3])`

### Simple Dataset (where it's possibile)
No dataset needed

### Steps (Mandatory)

  1. Not sure ...

## Screenshots (where it's possibile)
<img width="592" alt="Screen Shot 2022-10-30 at 1 24 25 AM" src="https://user-images.githubusercontent.com/231694/198863907-941754c2-8aed-453b-872a-975ad9bbbf57.png">

## Specifications (Mandatory)
Currently used versions

### Versions

  - OS: macOS 12.6.1
  - Neo4j: 5.1.0
  - Neo4j-Apoc: 5.1.0

**Comment by nadja-muller** [comment]
Thank you for reporting this.

I agree the documentation is contradicting itself.
In the usage example,  as the usage examples it is described that the procedure returns true if all values in the collections are different, which is the correct description.

We will update the documentation and get back to you.

**Comment by gem-neo4j** [comment]
Sorry for the slow reply, seems this got fixed without the issue being updated and you being replied to! 🙈 (release [5.4](https://github.com/neo4j/apoc/releases/tag/5.4.0))

So you want to know if all the items are the same or not? perhaps using the Cypher function `all` would work? e.g 

```
WITH [1,1,1,1] as list
RETURN all(a in list WHERE a = list[0])
```

vs

```
WITH [1,1,2,1] as list
RETURN all(a in list WHERE a = list[0])
```

Not sure if this helps, but we unfortunately aren't extending APOC core anymore so we can't add a new apoc.coll function! Thanks for reporting this issue though :)
