### ISSUE TITLE
Failed to read config `/var/lib/neo4j/conf/neo4j.conf`: Unrecognized setting. No declared setting with name: `apoc.export.file.enabled`

### ISSUE THREAD

**Issue by tekrei** [neo4j/apoc#233]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

Neo4j Docker container should run.

## Actual Behavior (Mandatory)

It is not running and giving the following error:

```
Failed to read config /var/lib/neo4j/conf/neo4j.conf: Unrecognized setting. No declared setting with name: apoc.export.file.enabled. Cleanup the config or disable 'server.config.strict_validation.enabled' to continue.

Run with '--verbose' for a more detailed error message.
```

### Steps (Mandatory)

Try to start a Docker container with the following command:

```
docker run --rm -it --name neo4j \
    -v /var/opt/neo4j/data:/data \
    -v /var/opt/neo4j/logs:/logs \
    -v /var/opt/neo4j/import:/var/lib/neo4j/import \
    -e NEO4J_AUTH=neo4j/test \
    -e NEO4J_dbms_default__listen__address=0.0.0.0 \
    -e NEO4J_dbms_default__advertised__address=localhost \
    -e NEO4J_dbms_connector_bolt_advertised__address=:7687 \
    -e NEO4J_dbms_connector_http_advertised__address=:7474 \
    -e NEO4J_PLUGINS='["apoc", "graph-data-science", "n10s"]' \
    -e NEO4J_dbms_unmanaged__extension__classes=n10s.endpoint=/rdf \
    -e NEO4J_apoc_export_file_enabled=true \
    -e NEO4J_apoc_import_file_enabled=true \
    -e NEO4J_apoc_import_file_use__neo4j__config=false \
    -e apoc.http.timeout.connect=0  \
    -e apoc.http.timeout.read=0  \
    --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1" \
    -p 7474:7474 -p 7687:7687 neo4j:latest
```

## Screenshots (where it's possible)

![image](https://user-images.githubusercontent.com/200193/200761645-981e6251-4106-411c-b160-2d313e20525d.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: **Windows WSL2 Ubuntu 22.04**
  - Neo4j: **neo4j:latest Docker image which is Neo4j 5.1.0 community edition**
  - Neo4j-Apoc: **The one inside the container**

**Comment by ncordon** [comment]
Hello @tekrei. Thanks for reporting!

Unfortunately this has been a change of behaviour between the 4.x versions and the 5.x ones. For the moment you can circumvent it by doing:

```
    -e apoc.export.file.enabled=true \
    -e apoc.import.file.enabled=true \
    -e apoc.import.file.use_neo4j_config=false \
```

instead of:

```
    -e NEO4J_apoc_export_file_enabled=true \
    -e NEO4J_apoc_import_file_enabled=true \
    -e NEO4J_apoc_import_file_use__neo4j__config=false \
```

**Comment by tekrei** [comment]
Hello @ncordon,

Thanks for the suggestion, I already tried that but I didn't able to confirm if these configuration are applied correctly.

They are not listed with `dbms.listConfig` command on browser, I can't find them in `conf/neo4j.conf` file and there is no `conf/apoc.conf` file available.

Any suggestion about how can I check if they are applied?

**Comment by cramatt** [comment]
I encountered this issue too and from the docs it looks like `export.file.enabled` is no longer a config option - https://neo4j.com/labs/apoc/5/config/

import is there (See screenshot)

![image](https://user-images.githubusercontent.com/22599518/206326559-56bbdce2-e7f6-4ce2-8690-bc5eaf6f8c5d.png)

Is this expected (behavior and config removed) or a bug?

**Comment by gem-neo4j** [comment]
Hi @cramatt, the export.file.enabled is considered a part of the Core config, so is mentioned specifically in the APOC Core docs here - https://neo4j.com/docs/apoc/current/config/ (the labs docs are for APOC extended only).

@tekrei you're correct they aren't listed in the list config, one option is to create an apoc.conf file yourself with your settings and add it into the conf directory.

e.g if I have one set up on my Desktop locally, I can add this to my Docker command

`-v $PWD/Desktop/apoc.conf:/var/lib/neo4j/conf/apoc.conf`

The you can see them here.

A hacky way of checking if they are set, is to check for the absence of the default getting set in the debug logs.

e.g 

`grep "APOC conf" logs/debug.log 
`
```
INFO  [a.ApocConfig] setting APOC config to default value: apoc.trigger.enabled=false
INFO  [a.ApocConfig] setting APOC config to default value: apoc.import.file.use_neo4j_config=true
INFO  [a.ApocConfig] setting APOC config to default value: apoc.export.file.enabled=false
INFO  [a.ApocConfig] setting APOC config to default value: apoc.import.file.enabled=false
```

And the ones (out of these 4) which are set by you will be missing from the logs.

Sorry it isn't a clearer answer, we are working on improving this 🙈

**Comment by jexp** [comment]
see https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3374
