### ISSUE TITLE
Support apoc.dump.jdbc

### ISSUE THREAD

**Issue by johnlinp** [neo4j/apoc#263]
**Is your feature request related to a problem? Please describe.**
I would like to dump data from Neo4j database into other relational databases, e.g. PostgreSQL.

**Describe the solution you'd like**
Just like [`apoc.load.jdbc`](https://neo4j.com/labs/apoc/5/database-integration/load-jdbc/), I would like to see a `apoc.dump.jdbc`.

**Describe alternatives you've considered**
I need to use a Spark application to load the data from Neo4j database and write into the relational database.

**Comment by johnlinp** [comment]
@mnd999 Thank you for the help.

**Comment by nadja-muller** [comment]
We are currenlty not extending apoc core. I'm moving your request to apoc extended.

**Comment by johnlinp** [comment]
Thank you. I've submitted https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3469.
