### ISSUE TITLE
Unable to find 4.x versions of APOC when running through docker

### ISSUE THREAD

**Issue by thordal-indykite** [neo4j/apoc#271]
## Expected Behavior (Mandatory)
The docker image should be able to find the 4.x versions of APOC.

## Actual Behavior (Mandatory)
We get this error:
`Error: No jar URL found for version '4.4.16' in versions.json from 'https://github.com/neo4j/apoc/blob/master/versions.json'`

## How to Reproduce the Problem
Add back the 4.x URLs or supply a workaround

### Steps (Mandatory)

  1. Run 
```
  docker run \                                                                                  
                     -p 7474:7474 -p 7687:7687 \
                     -v $PWD/data:/data -v $PWD/plugins:/plugins \
                     --name neo4j-apoc \
                     -e apoc.export.file.enabled=true \
                     -e apoc.import.file.enabled=true \
                     -e apoc.import.file.use_neo4j_config=true \
                     -e NEO4JLABS_PLUGINS=\[\"apoc\"\] \
                     --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes neo4j:4.4-enterprise
```
 
## Screenshots (where it's possibile)
![image](https://user-images.githubusercontent.com/110893808/210244389-6944c42b-9e57-4b19-baef-b1dfcbf0ed16.png)

## Specifications (Mandatory)

Neo4j 4.4-enterprise

**Comment by thordal-indykite** [comment]
Note that the versions exist in https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json

**Comment by thordal-indykite** [comment]
Duplicate in the Docker repo https://github.com/neo4j/docker-neo4j/issues/416

**Comment by AzuObs** [comment]
Hello Thordal,

I'm sorry you've encountered this issue, thank you so much for reporting it. 

We have a fix for it which is ready to go (https://github.com/neo4j/docker-neo4j/pull/417) and that we should be releasing tomorrow. 

In the meantime as a workaround you can use `-e NEO4JLABS_PLUGINS=\[\"apoc-core\"\]` which will actually make your job faster because it will use the apoc version which exists in the `/labs` directory of the docker image rather than download over the internet. Note that this will be the default behaviour in Neo4j 5.x.

**Comment by AzuObs** [comment]
Sorry for the delays in releasing the fix. We are working on a release but it's taking longer than expected. Please continue using the workaround and I will send updates once the release has been made.

**Comment by AzuObs** [comment]
The fix has now been released and everything should be back to normal. We've also added tests to make sure this particular scenario won't happen in the future.

Thank you all for your patience. Happy coding!

**Comment by madisonscott** [comment]
@AzuObs Thanks so much!

**Comment by madisonscott** [comment]
Hey @AzuObs, I believe this (or a similar) issue has resurfaced. We are seeing the following error trying to use the `4.4.enterprise` image with apoc:
```
   Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
   Installing Plugin 'apoc' from null to /var/lib/neo4j/plugins/apoc.jar 
  Error: Failed to initialize container neo4j:4.4-enterprise
```

It succeeds if we specify the `4.4.18-enterprise` image.

**Comment by AzuObs** [comment]
Hej Madison 👋 

Thank you for reporting this to us. I am so sorry it might be happening again. I will forward this to the team, and ask them to get back to you about it ASAP.

**Comment by Lojjs** [comment]
@madisonscott Thanks for reporting. It turned out that an update to the version.json file that specifies which Neo4j version should be used with which APOC version failed. We have applied a fix and it should now be working again. Please reach out again if you have further issues.
