### ISSUE TITLE
Parameter to make apoc.periodic.iterate() raise an error when any batch fails

### ISSUE THREAD

**Issue by johnlinp** [neo4j/apoc#284]
## Feature description (Mandatory)
I'm using `apoc.periodic.iterate()` to iterate nodes and perform actions on each node. Sometimes, some of the actions would fail. However, when any action fails, the call to `apoc.periodic.iterate()` is still successful. Therefore, the queries following the call will still be executed. I find it inconvenient because I don't want the following queries to be executed when the call to `apoc.periodic.iterate()` fails. In addition to that, I'm using `cypher-shell` command to execute by queries, and I want `cypher-shell` to exit with a non-zero status code if any of the action fails in the call to `apoc.periodic.iterate()`.

My proposal is to add a parameter (e.g. `raiseErrorWhenAnyBatchFail`) to `apoc.periodic.iterate()`, so I can config it to raise an error when any batch fails. That way, it can prevent the following queries to be executed and make `cypher-shell` exit with a non-zero status code when error occurs.

## Considered alternatives
I know that I can check the output parameters `failedOperations` and `failedBatches` that returned from the call to `apoc.periodic.iterate()` to know if the call has failed or not, but I didn't find any way to raise an error with the help of these 2 output parameters.

## How this feature can improve the project?
I guess it's a feature request that other people would find helpful.

**Comment by nadja-muller** [comment]
Hi. Thank you for adding this. We will look into it and come back to you.

**Comment by johnlinp** [comment]
Thank you!

**Comment by AzuObs** [comment]
The issue has been fixed by @johnlinp in this pull request https://github.com/neo4j/apoc/pull/304. Thank you so much for your contribution!

**Comment by johnlinp** [comment]
@AzuObs Excuse me, this issue has nothing to do with the PR #304. Please reopen this issue. Thank you.

**Comment by AzuObs** [comment]
Oops, you are right. Apologies for that.

**Comment by nadja-muller** [comment]
Hi @johnlinp. I will close this issue since we currently do not extend APOC core. Feel free to open a new github issue for [apoc extended](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues) if you think this functionality would fit in there.

**Comment by johnlinp** [comment]
I just reported at https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3547.
