### ISSUE TITLE
The missing constraint error message for apoc.import.json() is incorrect

### ISSUE THREAD

**Issue by johnlinp** [neo4j/apoc#290]
## Expected Behavior (Mandatory)

When executing `apoc.import.json()`, an error message for missing constraints might pop up and suggests a correct query to create the constraint.

## Actual Behavior (Mandatory)

The query suggested is incorrect and will not execute successfully.

### Steps (Mandatory)

  1. Run `apoc.import.json("sample.json");`
  1. See the error message that contains a suggested query: `CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS UNIQUE`
  1. Run the above query
  1. It shows `Invalid constraint syntax, ON and ASSERT should not be used. Replace ON with FOR and ASSERT with REQUIRE.`

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: macOS 12.4
  - Neo4j: 5.3.0
  - Neo4j-Apoc: 5.3.0

**Comment by AzuObs** [comment]
Fix by @johnlinp in https://github.com/neo4j/apoc/pull/304
