### ISSUE TITLE
Adding apoc.import.file.enabled=true would prevent db from starting

### ISSUE THREAD

**Issue by Firfi** [neo4j/apoc#319]
With APOC enabled, setting apoc.import.file.enabled=true would crash db on start.

- Neo4j version: 5.3.0
- Operating system: Ventura 13.2
- **Steps to reproduce**
1) Enable APOC for db
2) Run Db
3) Observe it runs
4) Add apoc.import.file.enabled=true to settings
<img width="901" alt="Screenshot 2023-01-30 at 9 48 56 PM" src="https://user-images.githubusercontent.com/947595/215510288-fd605314-5449-4f09-841b-8d6c18b90dfa.png">
5) Run db
- Expected behavior
db runs
- Actual behavior
db doesn't run
<img width="905" alt="Screenshot 2023-01-30 at 9 48 48 PM" src="https://user-images.githubusercontent.com/947595/215510397-82bcd766-e7b7-4aea-adb0-dd738190aaf4.png">

Before testing, I cleared up the logs directory. After the erroneous run, neo4j would create one empty file neo4j.log in logs directory. I'm not attaching it for the reason of its limited usefulness. I'm attaching desktop logs just because it's at least some logs to attach. Please not that the logs output is relatively the same in the case I run neo4j db without apoc.import.file.enabled=true
[renderer.log](https://github.com/neo4j/neo4j/files/10536876/renderer.log)

[main.log](https://github.com/neo4j/neo4j/files/10536874/main.log)

**Comment by greglu1976** [comment]
Same problem. Where did they hide apoc.conf?

**Comment by Lojjs** [comment]
Hi! Are you adding the setting to the `neo4j.conf` file? As of version 5, Apoc settings must be set either in the `apoc.conf` file or by environment variables, as described in [the APOC documentation](https://neo4j.com/docs/apoc/current/config/). To find or create an `apoc.conf` file from Browser you can click the ... next to you dbms -> Open folder -> Configuration.

The reason that it fails on startup is another change in Neo4j 5, where it by default does not start if there are unknown settings in the `neo4j.conf` file. If you want to avoid this you can add the following line to `neo4j.conf`: `server.config.strict_validation.enabled=false`. Note though that this will only ignore any apoc config setting in the `neo4j.conf` file and not apply  them.

  Best regards Louise, Neo4j engineering

**Comment by or-borr** [comment]
I am having the same problem when I add the apoc.import.file.enabled=true the instance will not start.

"Failed to read config /config/neo4j.conf: Unrecognized setting. No declared setting with name: apoc.export.file.enabled"

**Comment by nadja-muller** [comment]
@or-borr You need to create an apoc.conf file in the same folder as the neo4j.conf file and add the setting there. That should fix the problem.

**Comment by lxy1998** [comment]
add this line to neo4j.conf: server.config.strict_validation.enabled=false, I can run db but I can't run CALL apoc.import.csv. Please tell me how to fix it.

**Comment by lingvisa** [comment]
Same issue here

**Comment by Lojjs** [comment]
@lxy1998 and @lingvisa Have you tried following the instructions I posted above including creating a new apoc.conf file? As I wrote above, having apoc settings in neo4j.conf is not supported in Neo4j 5. The `neo4j.conf: server.config.strict_validation.enabled=false` will only ignore unknown settings and thus not throw an error on startup. The `apoc.import.file.enabled` needs to be set in apoc.conf or by using environment variables. If you still have problems after following the instructions in my message above, feel free to write what you did and what went wrong and I will try to help

**Comment by gem-neo4j** [comment]
Hi there! We've improved the [documentation](https://neo4j.com/docs/apoc/current/config/) around APOC config so hopefully this will help with the confusion :) 

I will close this as resolved, as I believe we have answered the original issues! Thanks
