### ISSUE TITLE
Aggregation function `toMap`

### ISSUE THREAD

**Issue by zirkelc** [neo4j/apoc#333]
## Feature description (Mandatory)
Aggregate all rows of a query into a single Map via user aggregation function, for example `apoc.coll.toMap(key, value)` or `apoc.map.fromRows(key, value)`.

Example: return a map of movie node ids to movie titles:
```cypher
MATCH (m:Movie) 
RETURN apoc.coll.toMap(toString(id(m)), m.title) as map
```
Returns:
```js
{
  "0": "The Matrix",
  "9": "The Matrix Reloaded",
  "10": "The Matrix Revolutions",
  // ...
}
```

## Considered alternatives
This is already possible with other APOC functions.
- apoc.map.fromPairs() + collect(): 
```cypher
MATCH (m:Movie) RETURN 
apoc.map.fromPairs(collect([toString(id(m)), m.title])) as map
```
- apoc.map.fromLists() + collect()
```cypher
MATCH (m:Movie) 
RETURN apoc.map.fromLists(collect(toString(id(m))), collect(m.title)) as map
```
- apoc.map.setEntry() + reduce()
```cypher
MATCH (m:Movie) 
RETURN reduce(map = {}, n IN collect(m) | apoc.map.setEntry(map, toString(id(n)), n.title)) AS map
```

## How this feature can improve the project?

All existing alternatives require an aggregation function (collect or reduce) plus an additional user function. Furthermore, an aggregation function `toMap` or `fromRows` seems like a good extension to the existing APOC functions.

---
I have already implemented such a user aggregation feature for my own project. If you think this is a good idea, I would submit a PR.

**Comment by gem-neo4j** [comment]
Hi there! Thank you for writing in. This is a great idea and nice to hear you've already implemented it for your own project! :) Unfortunately, APOC core is considered to be in maintenance mode and we are not currently extending it by adding new features.
