### ISSUE TITLE
Improve docs about configuration with env variables

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#37]
<a href="https://github.com/akshaymhetre"><img src="https://avatars.githubusercontent.com/u/2605952?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [akshaymhetre](https://github.com/akshaymhetre)**
_Wednesday Jul 28, 2021 at 02:44 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2120_

----

I am using neo4j with docker version 4.2.5 and cypher file to initialize data.

I am setting following environment property to initialize data with docker-compose -

NEO4J_apoc_initializer_cypher=CALL apoc.cypher.runFile ("file:///sample.cypher")

This works fine and load the data after server started. However, you cannot create indexes in this file. You need runSchema call to create indexes. As per doc for neo4j 4.2, you can run multiple cypher,

NEO4J_apoc_initializer_cypher_0=CALL apoc.cypher.runSchemaFile ("file:///schema.cypher")

NEO4J_apoc_initializer_cypher_1=CALL apoc.cypher.runFile ("file:///sample.cypher")

However, this throws error:

unknown settings: apoc.initializer.cypher.0

unknown settings: apoc.initializer.cypher.1

Raised [this](https://github.com/neo4j/docker-neo4j/issues/290) on neo4j docker site as well.

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Wednesday Jul 28, 2021 at 09:29 GMT_

----

@akshaymhetre can you please try with?:
```
apoc_initializer_cypher_0=CALL apoc.cypher.runSchemaFile ("file:///schema.cypher")
apoc_initializer_cypher_1=CALL apoc.cypher.runFile ("file:///sample.cypher")
```
Looking forward to hearing from you!

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/aowss"><img src="https://avatars.githubusercontent.com/u/6297886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aowss](https://github.com/aowss)**
_Wednesday Jul 28, 2021 at 12:10 GMT_

----

Sorry @conker84 , i am confused. I might not have understood your comment correctly.
Are you suggesting to just drop the leading `NEO4J_` part?

That's strange because :

- all the docs ( including some of your comments on other issues ) mention that prefix
- all the other environment variables seem to start with that prefix
- the error message `unknown settings: apoc.initializer.cypher.0` seems to have stripped that prefix

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Wednesday Jul 28, 2021 at 14:03 GMT_

----

> Sorry @conker84 , i am confused. I might not have understood your comment correctly.
> Are you suggesting to just drop the leading `NEO4J_` part?
> 
> That's strange because :
> 
> * all the docs ( including some of your comments on other issues ) mention that prefix
> * all the other environment variables seem to start with that prefix
> * the error message `unknown settings: apoc.initializer.cypher.0` seems to have stripped that prefix

Yes @aowss you understood correctly, we leverage under-the-hood Apache Configuration that should be capable of recognising that kind of env variable and configure APOC properly.
I did a mistake in the copy and paste in the previous comment, use this env variable:

```
apoc.initializer.cypher.0=CALL apoc.cypher.runSchemaFile ("file:///schema.cypher")
apoc.initializer.cypher.1=CALL apoc.cypher.runFile ("file:///sample.cypher")
```

As I said Apache Configuration should be capable of understanding these.
Please lemme know

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/conker84"><img src="https://avatars.githubusercontent.com/u/1833335?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conker84](https://github.com/conker84)**
_Wednesday Jul 28, 2021 at 15:51 GMT_

----

We definitely need to update the docs, I'm sorry I was sure that we did it in the past. I'll change the title of the issue

**Comment by hvub** [comment]
`apoc.initializer.cypher` is part of APOC and are documented [here](https://neo4j.com/docs/apoc/current/operational/).

`NEO4J_ ...` environment variables a part of the Neo4j docker images and are documented [here](https://neo4j.com/docs/operations-manual/current/docker/ref-settings/). Note that this page does not list the APOC environment variables.

The mechanism that picks up these two distinct set of environment variables is different. Likewise, they go to different configuration files in a non-docker setting (apoc.conf vs. neo4j.conf).

Nevertheless, the examples [here](https://neo4j.com/docs/apoc/current/installation/#docker) are indeed wrong. I have issued a correction and clarification and it will show in the documentation in due time.

**Comment by hvub** [comment]
Correction: The use of the NEO4J_ also for docker is correct since the following fix: https://github.com/neo4j/docker-neo4j/pull/409/

Nevertheless, the issue has been addressed.
