### ISSUE TITLE
requesting apoc-#.#.#.#-core.jar be available from maven

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#38]
<a href="https://github.com/Dcanzano"><img src="https://avatars.githubusercontent.com/u/16004526?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Dcanzano](https://github.com/Dcanzano)**
_Wednesday Aug 04, 2021 at 19:46 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2147_

----

## Feature description (Mandatory)
requesting apoc-<version>-core.jar, i.e. the same which is delivered to labs/ be available via a maven repository.  Today the only thing available it apoc-<version>-all.jar

## How this feature can improve the project?
Would like to download apoc-<version>-core.jar via maven as it is same as what is in labs\

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/klauspgross"><img src="https://avatars.githubusercontent.com/u/54915723?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [klauspgross](https://github.com/klauspgross)**
_Friday Aug 20, 2021 at 18:47 GMT_

----

We are using only the capabilities exposed in the core in our product and don't want to include the entire tar ball of apoc in our deployment.  To do this, our CI/CD pipeline requires a maven repository and we don't want to maintain our own for apoc-core maven repo

**Comment by ncordon** [comment]
Hey @Dcanzano, the jars for core will be published for the 5.x version onwards: https://mvnrepository.com/artifact/org.neo4j.procedure/apoc-core/5.0.0 💃
