### ISSUE TITLE
Add json5 support to apoc-core and extended

### ISSUE THREAD

**Issue by jexp** [neo4j/apoc#416]
Json5 adds a number of nice features. 

In jackson we can enable most of them with capabilities. Some of which we already do. 

See

https://stackoverflow.com/questions/68312227/can-the-jackson-parser-be-used-to-parse-json5

**Comment by gem-neo4j** [comment]
Would it make more sense to have suggestions like this as Trello cards instead of issues on Github? :)

**Comment by hvub** [comment]
Cardified. Closing here.
