### ISSUE TITLE
APOC version 5.8

### ISSUE THREAD

**Issue by gongomgra** [neo4j/apoc#421]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Feature description (Mandatory)
I'm trying to run Neo4j 5.8.0 ([released last week](https://github.com/neo4j/neo4j/releases/tag/5.8.0)) with the corresponding APOC version in order to meet the [versioning requirements](https://github.com/neo4j/apoc#manual-installation-download-the-latest-release). However, APOC 5.8.x hasn't been released yet. Do you have any estimation on when will it be released? 

Thanks in advance!

**Comment by ncordon** [comment]
Hey @gongomgra! It should be available now, thanks for reporting 😄
