### ISSUE TITLE
Feature Request: measures the Cosine similarity of two vectors of an inner product space and compares the angle between them

### ISSUE THREAD

**Issue by dmitrydivin** [neo4j/apoc#458]
Hi,

Apache commons library has a function [CosineSimilarity.java](https://github.com/apache/commons-text/blob/9fdc137eafff15a83bf8ca071e9322a7e1452654/src/main/java/org/apache/commons/text/similarity/CosineSimilarity.java) to find similar documents.

How it works?

A document can be represented by thousands of attributes, each recording the frequency of a particular word (such as a keyword) or phrase in the document. Thus, each document is an object represented by what is called a term-frequency vector.

I have used this approach in [content-based recommendation system from the open source unsplash dataset](http://185-167-97-116.cloud-xip.com/).

## Feature description (Mandatory)

This function can be implemented as:
```java
    @UserFunction
    public Double cosineSimilarity(@Name("leftVector") Map<String, Double> leftVector,
                                   @Name("rightVector") Map<String, Double> rightVector) {
        Set<String> intersection = new HashSet<>(leftVector.keySet());
        intersection.retainAll(rightVector.keySet());
        double dotProduct = 0.0;
        for (String key : intersection) {
            dotProduct += leftVector.get(key) * rightVector.get(key);
        }
        double d1 = 0.0d;
        for (Double value : leftVector.values()) {
            d1 += Math.pow(value, 2);
        }
        double d2 = 0.0d;
        for (Double value : rightVector.values()) {
            d2 += Math.pow(value, 2);
        }
        double cosineSimilarity;
        if (d1 <= 0.0 || d2 <= 0.0) {
            cosineSimilarity = 0.0;
        } else {
            cosineSimilarity = dotProduct / (Math.sqrt(d1) * Math.sqrt(d2));
        }
        return cosineSimilarity;
    }
```

Using the following example, you can check how it works:

Adding four classifiers:
```cql
create (:Classifier{keyword: 'animals'})
create (:Classifier{keyword: 'cat'})
create (:Classifier{keyword: 'dog'})
create (:Classifier{keyword: 'car'})
```

Then we will add three objects that will have relationships to classifiers with a `accuracy` property.

```cql
create (o:Object{title: 'my cat'})
with o, [{keyword: "animals", accuracy: 1.0}, {keyword: "cat", accuracy: 0.8}] as classifiers
unwind classifiers as classifier
match (c:Classifier) where c.keyword = classifier.keyword
create (o)-[:IS_ASSOCIATED_WITH{accuracy: classifier.accuracy}]->(c)
```

```cql
create (o:Object{title: 'my dog'})
with o, [{keyword: "animals", accuracy: 1.0}, {keyword: "dog", accuracy: 0.75}] as classifiers
unwind classifiers as classifier
match (c:Classifier) where c.keyword = classifier.keyword
create (o)-[:IS_ASSOCIATED_WITH{accuracy: classifier.accuracy}]->(c)
```

```cql
create (o:Object{title: 'my car'})
with o, [{keyword: "car", accuracy: 1.0}] as classifiers
unwind classifiers as classifier
match (c:Classifier) where c.keyword = classifier.keyword
create (o)-[:IS_ASSOCIATED_WITH{accuracy: classifier.accuracy}]->(c)
```

If we try to present our pivot table of all classifiers to the objects, we get:

![Снимок экрана 2023-07-22 в 15 25 42](https://github.com/neo4j/apoc/assets/479428/2c67629f-9077-4e68-ba51-dd609ca84916)

Let's compare one of the object with others with the following query:
```cql
match (o:Object{title: 'my dog'})-[r:IS_ASSOCIATED_WITH]->(c:Classifier)
with o, apoc.map.fromPairs(collect([ID(c), r.accuracy])) as leftVector
match (s:Object)-[r:IS_ASSOCIATED_WITH]->(c:Classifier)
with leftVector, o, s, apoc.map.fromPairs(collect([ID(c), r.accuracy])) as rightVector
with o.title as obj_title, s.title as similar_obj_title, cosineSimilarity(leftVector, rightVector) as score
return obj_title, similar_obj_title, score
order by score desc
```

Then we get the following result:
![Снимок экрана 2023-07-22 в 15 28 38](https://github.com/neo4j/apoc/assets/479428/6b21591a-94ac-49a6-b48e-c6a445b8916b)

Thus it is possible to find similar objects at a time when their classifiers are at the intersection an inner product space.

## Considered alternatives
You need much more code in the Cypher language with the `gds.similarity.cosine` to get the same result with the following query:

```cql
match (o:Object{title: 'my dog'})-[r:IS_ASSOCIATED_WITH]->(c:Classifier)
with o, apoc.map.fromPairs(collect([ID(c), r.accuracy])) as leftVector, apoc.map.fromPairs(collect([ID(c), 0.0])) as leftZeroVector
match (s:Object)-[r:IS_ASSOCIATED_WITH]->(c:Classifier)
with leftVector, leftZeroVector, o, s, apoc.map.fromPairs(collect([ID(c), r.accuracy])) as rightVector, apoc.map.fromPairs(collect([ID(c), 0.0])) as rightZeroVector
with o.title as obj_title, s.title as similar_obj_title, [c IN apoc.map.sortedProperties(apoc.map.merge(rightZeroVector, leftVector)) | c[1]] as l_vector, [c IN apoc.map.sortedProperties(apoc.map.merge(leftZeroVector, rightVector)) | c[1]] as r_vector
with obj_title, similar_obj_title, gds.similarity.cosine(l_vector, r_vector) as score
return obj_title, similar_obj_title, score
order by score desc
```

Then we get the same result:
![Снимок экрана 2023-07-22 в 16 57 00](https://github.com/neo4j/apoc/assets/479428/eb3cb90c-91f1-409c-9329-e494041786b1)

## How this feature can improve the project?

Hight performance and easy way to similarity two vectors of an inner product space with the cosine similarity.

## Related links
- [Cosine Similarity on the sciencedirect](https://www.sciencedirect.com/topics/computer-science/cosine-similarity)

**Comment by Lojjs** [comment]
@dmitrydivin The APOC core project is currently in sort of a maintenance/stabilization mode where we mainly fix bugs and security issues and do not add new features. Could I therefore ask you to re-open your feature request in the repo for APOC Extended here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues 

Best wishes Louise, Neo4j

**Comment by dmitrydivin** [comment]
@Lojjs Thanks for your reply. I will create issue in another space.
