### ISSUE TITLE
apoc.custom fully removed???!!!

### ISSUE THREAD

**Issue by Hassankmkr** [neo4j/apoc#471]
## Expected Behavior (Mandatory)
I need to create a custom function using apoc.custom.declareFunction as mentioned in the [article](https://towardsdatascience.com/hdbscan-clustering-with-neo4j-57e0cec57560). 

## Actual Behavior (Mandatory)
I faced "There is no procedure with the name `apoc.custom.declareFunction` registered for this database instance." 
I searched SHOW PROCEDURES yield name, description, signature and found there is no apoc.custom listed there!!

## How to Reproduce the Problem
call apoc.custom.declareFunction('getLastCluster',
"MATCH (n) where id(n) = id($n)
WITH n MATCH clustPath = (n)-[:IN_CLUSTER*0..]->(c)
WITH clustPath order by length(clustPath) desc
LIMIT 1
RETURN nodes(clustPath)[-1] as lastCluster",
"NODE",
[["n","NODE"]],
false,
"Starting from a given node, get the node at the end of the longest path of IN_CLUSTER relationships")

### Simple Dataset (where it's possibile)
not needed here.
```
//Insert here a set of Cypher statements that helps us to reproduce the problem
call apoc.custom.declareFunction('getLastCluster',
"MATCH (n) where id(n) = id($n)
WITH n MATCH clustPath = (n)-[:IN_CLUSTER*0..]->(c)
WITH clustPath order by length(clustPath) desc
LIMIT 1
RETURN nodes(clustPath)[-1] as lastCluster",
"NODE",
[["n","NODE"]],
false,
"Starting from a given node, get the node at the end of the longest path of IN_CLUSTER relationships")
```

### Steps (Mandatory)

  1. Just run the above cypher code and you will get the error.

## Specifications (Mandatory)

Required alternative function in apoc to build custom functions.

### Versions

  - OS:
  - Neo4j: 5.10.0
  - Neo4j-Apoc: 5.10.1

**Comment by gem-neo4j** [comment]
Hi there! As of 5.0 APOC got split into APOC core and APOC extended. The procedure you are talking about is a part of APOC extended, you can download the jar from [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/5.10.0) and load it into your db :) Hope that helps!

To see which procedures are in core see [here](https://neo4j.com/docs/apoc/current/overview/)
To see which procedures are in extended see [here](https://neo4j.com/labs/apoc/5/overview/)
