### ISSUE TITLE
file:/// urls don't work with apoc.export.*

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#48]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Tuesday Aug 17, 2021 at 11:00 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2179_

----

```
neo4j@neo4j> call apoc.export.csv.all("file:///movies.csv",{});
Failed to invoke procedure `apoc.export.csv.all`: Caused by: java.io.FileNotFoundException: /var/lib/neo4j/import/file:/movies.csv (No such file or directory)
neo4j@neo4j> call apoc.export.csv.all("file://movies.csv",{});
Failed to invoke procedure `apoc.export.csv.all`: Caused by: java.io.FileNotFoundException: /var/lib/neo4j/import/file:/movies.csv (No such file or directory)

```

**Comment by gem-neo4j** [comment]
This seems to have been fixed :)
