### ISSUE TITLE
Can we get an quick investigation (added to this issue or docs) what happens when a new multi-database is created/started in neo4j?

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#49]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Tuesday Aug 17, 2021 at 11:06 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2180_

----

i.e.

* which extension factories are started / restarted on a per db basis
* which things are re-initialized
* what did we do in apoc to accommodate for multi-db so far
*

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/eastlondoner"><img src="https://avatars.githubusercontent.com/u/8148776?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eastlondoner](https://github.com/eastlondoner)**
_Tuesday Aug 17, 2021 at 11:26 GMT_

----

Example (on a cluster):

```
CALL apoc.export.csv.all("file:///movies.csv", {});
<success>

CREATE DATABASE movies WAIT;
CALL apoc.export.csv.all("file:///movies.csv", {});
Failed to invoke procedure `apoc.export.csv.all`: Caused by: java.io.FileNotFoundException: /data/databases/movies/temp-bootstrap/file:/movies.csv (No such file or directory)
```

**Comment by loveleif** [comment]
Inactive for two years, closing. Please open a new issue if this is still an issue.
