### ISSUE TITLE
Typo in triggers documentation

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#50]
<a href="https://github.com/papaonlegs"><img src="https://avatars.githubusercontent.com/u/856612?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [papaonlegs](https://github.com/papaonlegs)**
_Monday Aug 23, 2021 at 15:33 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2188_

----

https://neo4j.com/labs/apoc/4.2/background-operations/triggers/

It says delated, instead of deleted, in the description of `deletedNodes` and `deletedRelationships`

**Comment by gem-neo4j** [comment]
Looks like it has been updated :)
