### ISSUE TITLE
The apoc.export.csv.all doesn't export quotes with bulkImport: true

### ISSUE THREAD

**Issue by vga91** [neo4j/apoc#516]
## Expected Behavior (Mandatory)

Should export the `"` (escaped).

## Actual Behavior (Mandatory)

The `"` is not exported.

## How to Reproduce the Problem

Create some nodes with a quote, e.g.:
```
CREATE (n:DoubleQuoteTest {text:'This is a double quote "'});
CREATE (n:DoubleQuoteTest2 {text:'This is a " double quote2'});
```

The export without bulkImport print the `"` char as a `""` (to escape it).

```
CALL apoc.export.csv.all("doublequotedb.csv", {quotes:'always'});
```

Output file `doublequotedb.csv`:
```
"_id","_labels","text","_start","_end","_type"
"0",":DoubleQuoteTest","This is a double quote """,,,
"1",":DoubleQuoteTest2","This is a "" double quote2",,,
```

On the contrary, with bulkImport, the `"` is not printed.
```
CALL apoc.export.csv.all("doublequoteimportdb.csv", {bulkImport:true, quotes:'always'});
```

Output file `doublequoteimportdb.nodes.DoubleQuoteTest.csv`:
```
:ID,text,:LABEL
0,This is a double quote ,DoubleQuoteTest
```

Output file `doublequoteimportdb.nodes.DoubleQuoteTest2.csv`:
```
:ID,text,:LABEL
1,This is a  double quote2,DoubleQuoteTest2
```

### Versions

  - Neo4j: 4.4.26 (most likely with every version)
  - Neo4j-Apoc: 4.4.0.22  (most likely with every version)

**Comment by Lojjs** [comment]
This has been fixed during October, so will close the issue.
