### ISSUE TITLE
Improve error handling with s3 and hdfs protocols

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#55]
<a href="https://github.com/vga91"><img src="https://avatars.githubusercontent.com/u/25103389?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vga91](https://github.com/vga91)**
_Friday Sep 17, 2021 at 13:38 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2212_

----

## Expected Behavior (Mandatory)

Should return `apoc.util.MissingDepencencyException` similarly to `MongoDb` and `Couchbase` procs. 

## Actual Behavior (Mandatory)

Return `java.net.MalformedURLException: unknown protocol: s3` or `unknown protocol: hdfs`

## How to Reproduce the Problem

Call any export/import/load procedure with a protocol `s3` or `hdfs`. For example:
```
CALL apoc.load.csv('s3://MY_S3_URL')
```

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Mac BigSur
  - Neo4j: 4.2.7
  - Neo4j-Apoc: 4.2.0.5

**Comment by vga91** [comment]
The issue is no longer present with apoc 4.3+
