### ISSUE TITLE
apoc.meta.data() fails when there is a relationship-type `RELATIONSHIP` breaks GenAI integrations

### ISSUE THREAD

**Issue by jexp** [neo4j/apoc#583]
When you have a graph with a `RELATIONSHIP` the current apoc.meta.data() implementation breaks with this exception.

Failed to invoke procedure `apoc.meta.data`: Caused by: java.lang.IllegalArgumentException: duplicate element: RELATIONSHIP

As we use this in the schema generation for our genai-integrations, this breaks them and the applications using them.

**Comment by kamzz1107** [comment]
same issue I have faced today while calling apoc.meta.data()

**Comment by mfreeman451** [comment]
this was marked completed and closed, but its not clear why? where is the fix? I'm having this same issue.

**Comment by mfreeman451** [comment]
is there an earlier release that doesn't have this bug?

**Comment by gem-neo4j** [comment]
The linked PR request fixes it, but the fix itself will be released in 5.18 :)

**Comment by mfreeman451** [comment]
> The linked PR request fixes it, but the fix itself will be released in 5.18 :)

What is the release cadence for neo4j?
