### ISSUE TITLE
Failed to invoke procedure `apoc.meta.data`: Caused by: java.lang.IllegalArgumentException: duplicate element: RELATIONSHIP

### ISSUE THREAD

**Issue by Chal1ce** [neo4j/apoc#599]
### Steps (Mandatory)
  1. CREATE (a:NODE)-[r:RELATIONSHIP]->(m:Movie)
  2. CALL apoc.meta.data()

## Screenshots (where it's possibile)
![image](https://github.com/neo4j/apoc/assets/103374522/a68436ca-7d8c-46a2-b23f-87232fe95c6d)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: MacOS
  - Neo4j: 5.16.0
  - Neo4j-Apoc: 5.16.1

**Comment by Chal1ce** [comment]
I noticed that this has been fixed, but I can't find version 5.17 of neo4j, and it's not clear how apoc-core is supposed to be installed

**Comment by Chal1ce** [comment]
With version 5.17.0 of apoc this still occurs.

OS: MacOS
Neo4j: 5.17.0
Neo4j-Apoc: 5.17.0

**Comment by gem-neo4j** [comment]
Hi! Yes, it was fixed recently, but the fix is not being released until 5.18, which is next month :)

**Comment by Chal1ce** [comment]
Got it. Thanks.
