### ISSUE TITLE
[apoc.spatial.geocodeOnce] Run failed

### ISSUE THREAD

**Issue by zyh20011** [neo4j/apoc#617]
To help us understand your issue, please specify important details, primarily:

- Neo4j version: 5.12.0 (desktop)
- Operating system: Windows 11

An error occurred while running the apoc space instance：
![apoc](https://github.com/neo4j/neo4j/assets/125949405/6a1b80ba-7db9-4345-91c6-6111d25407c0)

I manually installed on the desktop version, automatic installation will also encounter this error.

**Comment by Lojjs** [comment]
@zyh20011 Hi! I wonder if the geocode server can have been unavailable or something like that just when you tried this query. If you test it again today, do you get the same result? 

If I try out the same query on Desktop 5.12 I get an answer which looks sensible after about 1 second.

Best regards Louise, Neo4j

**Comment by zyh20011** [comment]
ok， i‘ll try it again
