### ISSUE TITLE
Schedule task for one-off execution at specified time

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#63]
<a href="https://github.com/magaton"><img src="https://avatars.githubusercontent.com/u/4103157?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [magaton](https://github.com/magaton)**
_Monday Nov 22, 2021 at 13:16 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2373_

----

## Feature description (Mandatory)
There is currently no way to schedule a statement to be executed at the specified time

## Considered alternatives
`apoc.perodic.submit`, does not accept time
`apoc.periodic.countdown` requires statement to return 0.

## How this feature can improve the project?
I would like to schedule an update in the graph.

**Comment by hvub** [comment]
Yes, there is no proper job scheduling facility. 

However, you can use `apoc.cypher.doIt` in combination with `apoc.util.sleep` and Cypher temporal functions to schedule something like this:

```
WITH 
  localdatetime({
    year: 2024, month: 11, day: 19,
    hour: 11, minute: 7, second: 0
  }) AS target,
  localdatetime() AS now
WITH now, target, duration.inSeconds(now, target).milliseconds AS inMillis 
CALL apoc.cypher.doIt("CALL apoc.util.sleep($inMillis) CREATE (w:WaitForMe) RETURN w", {inMillis: inMillis}) YIELD value
RETURN value
```

cf.
- https://neo4j.com/docs/cypher-manual/current/functions/temporal/#functions-localdatetime
- https://neo4j.com/docs/cypher-manual/current/functions/temporal/duration/#functions-duration-inseconds
- https://neo4j.com/docs/cypher-manual/current/values-and-types/temporal/#cypher-temporal-accessing-components-durations

I recommend to check the times first to see if the timezone work out as expected, e.g. like this:
```
WITH 
  localdatetime({
    year: 2024, month: 11, day: 19,
    hour: 11, minute: 7, second: 0
  }) AS target,
  localdatetime() AS now
WITH now, target, duration.inSeconds(now, target).milliseconds AS inMillis 
RETURN RETURN *
```
