### ISSUE TITLE
single node handling in apoc.refactor.mergeNodes

### ISSUE THREAD

**Issue by TomVanWemmel** [neo4j/apoc#644]
In `apoc.refactor.mergeNodes` there is no check on equality between the given nodes. 
All relationships are iterated to check that they would refer to the node itself. 
It might be beneficial to return early when the node has many relationships.

**Comment by gem-neo4j** [comment]
Hi! The nodes are turned into a linked set before being processed, so they should be unique and none of them should match the first node :)
