### ISSUE TITLE
在添加APOC时出现Variable`apoc`not defined的问题

### ISSUE THREAD

**Issue by 244607753** [neo4j/apoc#673]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
我是要安装APOC

## Actual Behavior (Mandatory)
计划使用APOC

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.因为从官网上看到的是5.X以上版本相关的jar包已经放入了labs包里，只需要将相关jar包放入plugins里就好了
  2.同时我也修改了相关配置，所以我觉得应改不会出现该类错误。
  3.我之前用的4.4版本也进行同样的操作，是可以使用的。
  4.我后来又从neo4j github上下载了apoc的jar包，并且看了版本兼容性。

## Screenshots (where it's possibile)
我会发送一些截图
![版本](https://github.com/user-attachments/assets/a75b9554-b61d-42db-b923-a4f7b61a7ebb)
![配置文件](https://github.com/user-attachments/assets/15b0d086-f74f-4485-b241-ecb5486d4777)
![showfunction](https://github.com/user-attachments/assets/9d8d825d-af8b-483d-bba1-dfc6e70e7c57)
![报错](https://github.com/user-attachments/assets/c71eca6a-9290-4d23-8dd2-e0510bc69018)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:neo4j-community-5.23.0
  - Neo4j-Apoc:apoc-5.23.0-core.jar

**Comment by loveleif** [comment]
@244607753 I'm sorry, me or none of my team members can't read your language (Chinese?). Is it possible to translate your issue to English?

**Comment by 244607753** [comment]
1. Because what you see from the official website is 5. The JAR packages related to the above X versions have been put into the labs package, and you only need to put the relevant JAR packages into the plugins
2. At the same time, I have also modified the relevant configuration, so I don't think there will be such an error.
3. I used the same 4.4 version before, and it can be used.
4. I later downloaded the APOC jar package from Neo4j GitHub and looked at version compatibility.

**Comment by 244607753** [comment]
I sent some pictures above, you guys help me take a look, thank you very much.

**Comment by 244607753** [comment]
Anyway, my problem is that I'm using apoc.version with an error

**Comment by gem-neo4j** [comment]
Hi! functions need to always be appended with parenthesis to work;

`RETURN apoc.version()`
