### ISSUE TITLE
Failed to invoke procedure `apoc.meta.schema` : Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#69]
<a href="https://github.com/xiajing10"><img src="https://avatars.githubusercontent.com/u/49093092?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xiajing10](https://github.com/xiajing10)**
_Thursday May 27, 2021 at 18:55 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1934_

----

## Specifications (Mandatory)
Cannot run `CALL apoc.meta.schema()` in browser

Error
```
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.meta.schema`: Caused by: java.lang.NullPointerException
```

### Versions

  - OS: Windows 10
  - Neo4j: browser 4.2.6
  - Neo4j-Apoc: 4.2.0.4

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/vga91"><img src="https://avatars.githubusercontent.com/u/25103389?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vga91](https://github.com/vga91)**
_Friday Sep 10, 2021 at 13:21 GMT_

----

@xiajing10 
I tried the same neo4j and apoc version without any problem.
Can you to upgrade the apoc version and, if the problem is still present, 
can you send a dataset to replicate the error?

**Comment by gem-neo4j** [comment]
Closing as not able to reproduce.
