### ISSUE TITLE
Apoc.periodic.submit procedure was entered with no errors thrown but the procedure did not go through.

### ISSUE THREAD

**Issue by FaezSubmarine** [neo4j/apoc#695]
## Expected Behavior (Mandatory)
That the query written within the procedure would be executed in the background.

## Actual Behavior (Mandatory)
The query did not execute at all.

### Simple Dataset (where it's possible)

```
MERGE (s:Setting) ON CREATE SET s.timeOut = duration({seconds:1000}) return s
```

```
CALL apoc.periodic.submit(
             "example",
             'CREATE (p:Person {name: "Michael Hunger", datePosted:datetime()})
             WITH p
             MATCH (s:Setting)
             CALL apoc.util.sleep(s.sleepTime)
             DELETE p
            ')
```

```
Call apoc.periodic.cancel("example")
           CALL apoc.periodic.submit(
             "example",
             'MATCH (s:Setting)
              MATCH(p:Person{name:'Michael Hunger'})
  	      with duration.between(datetime(), p.datePosted+s.sleepTime) as d,s,p
  	      CALL apoc.util.sleep(d.Seconds)
  	      DELETE p
            ')
```
### Steps (Mandatory)

  1. Write a submit procedure where it contains apoc.util.sleep and then it deletes a node.
  2. 'Update' the procedure by cancelling it and calling a new one with the same name and almost the same procedure but with updated duration(see: the cypher above or the explanation in my own post below)
  3. Observe changes(or lack thereof)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows
  - Neo4j: 5.25-Aura
  - Neo4j-Apoc: 5.25.1

**Comment by gem-neo4j** [comment]
Hi there! This query worked for me on those versions, do you have any more information? Can you see anything in the debug log or query logs about it?

**Comment by FaezSubmarine** [comment]
Hi Gem! So soon after you sent your message, I checked the database, and the apoc periodic submit procedures that I had sent had just gone through, IE there is now Persons node created, so I assume the problem was fixed along the way or it solved itself in the background. However, when I tried to proceed with my project, the bug returned. Also, AuraDB don't let me check its logs as I am on the free tier.

I assume that what I was doing was causing the issue, so I should provide more context of what I was doing.

So let's say that the database has a setting node created like this.

```
Create (s:setting{sleepTime:1000}) return s
```
Let's assume that this procedure had already been executed
```
CALL apoc.periodic.submit(
             "example",
             'CREATE (p:Person {name: 'Michael Hunger,datePosted:datetime()'})
             MATCH (s:Setting)
             CALL apoc.util.sleep(s.sleepTime)
             DELETE p
            ')
```
I would like to implement a feature where the user can change how long the sleep time lasts, but if the sleep time had changed then I would need to update the procedure so the timing matches up. If the person node's datePosted plus updated sleep time is ahead of datetime(), then the following cypher will subtract the difference and make that diff the new sleep time. If the person node's datePosted plus sleep time is behind datetime(), then sleep will be done instantly and continue with the rest of the procedure. I implemented it this way because I noticed that if apoc.util.sleep was given negative numbers, it would be done instantly. The cypher is like so:

```
Call apoc.periodic.cancel("example")
           CALL apoc.periodic.submit(
             "example",
             'MATCH (s:Setting)
              MATCH(p:Person{name:'Michael Hunger'})
  	      with duration.between(datetime(), p.datePosted+s.sleepTime) as d,s,p
  	      CALL apoc.util.sleep(d.Seconds)
  	      DELETE p
            ')
```

I will update the original post accordingly.

**Comment by gem-neo4j** [comment]
Hi there!

I am unsure if these are your real queries or not, but there are a few issues with them. 

`Create (s:setting{sleepTime:1000}) return s`
Should be:
`Create (s:Setting{sleepTime:1000}) return s`

```
CALL apoc.periodic.submit(
             "example",
             'CREATE (p:Person {name: 'Michael Hunger,datePosted:datetime()'})
             MATCH (s:Setting)
             CALL apoc.util.sleep(s.sleepTime)
             DELETE p
            ')
```
Should be; Note the the quotation around the properties, without this, it means your nodes don't have a datePosted property and that would return null, and a WITH is needed between a CREATE and a MATCH
```
CALL apoc.periodic.submit(
             "example",
             'CREATE (p:Person {name: "Michael Hunger", datePosted:datetime()})
             WITH p
             MATCH (s:Setting)
             CALL apoc.util.sleep(s.sleepTime)
             DELETE p
            ')
```


The for these ones;
`Call apoc.periodic.cancel("example")`

```
           CALL apoc.periodic.submit(
             "example",
             'MATCH (s:Setting)
              MATCH (p:Person{name:'Michael Hunger'})
  	      with duration.between(datetime(), p.datePosted+s.sleepTime) as d,s,p
  	      CALL apoc.util.sleep(d.Seconds)
  	      DELETE p
            ')
```

You cannot add a datetime (d.datePosted) with an int (s.sleepTime), so this also will not work.


Have you tried all the queries you are submitting in the procedure outside of the queries? It could be that the procedure is swallowing an error that the query is writing.

**Comment by gem-neo4j** [comment]
Hi again :) 

I tested this out, and it works for me, so unfortunately there isn't much more I can do.

Just some things to note:
apoc.util.sleep takes a time in milliseconds, you have been talking about seconds here, so just want to make sure that is clear.
There are guards for the length of a running query, I am unsure how long that is in Aura, but there is always a chance if your query is too long running it gets cancelled.
If the node hasn't been deleted, try running apoc.periodic.list to see if the periodic query is still considered "non-completed" that might give you some insight into what is happening.
Another option would be to run apoc.periodic.repeat, and instead of sleeping and blocking a thread, you could then just check the time and delete if the time has passed or not, then you don't need to keep submitting new queries
