### ISSUE TITLE
Document coding style rules

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#70]
<a href="https://github.com/fbiville"><img src="https://avatars.githubusercontent.com/u/445792?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fbiville](https://github.com/fbiville)**
_Friday May 28, 2021 at 15:48 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1936_

----

Target: `CONTRIBUTING.md`.

Ideally, automate it. Possible options for that:
 - https://editorconfig.org/
 -  IntelliJ settings JAR
 - ...
 
 Ideally, the automated coding style generates as little change as possible in the codebase.

**Comment by JoelBergstrand** [comment]
Resolved in commit [dfcbbea](https://github.com/neo4j/apoc/commit/dfcbbea31b2685913656023500d06ba1b555281a)
