### ISSUE TITLE
Missing apoc.export.csv.all.

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#72]
<a href="https://github.com/cn007b"><img src="https://avatars.githubusercontent.com/u/5052324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cn007b](https://github.com/cn007b)**
_Monday Dec 21, 2020 at 13:47 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1757_

----

Guidelines
There is function [apoc.export.csv.all](https://neo4j.com/labs/apoc/4.1/overview/apoc.export/apoc.export.csv.all/) but no function [apoc.import.csv.all](https://neo4j.com/labs/apoc/4.1/overview/apoc.import/apoc.import.csv/),
and it's not clear how to import CSV file generated by func apoc.export.csv.all.

Neo4j Version: 4.1.1
API: Docker
Source: [This page](https://github.com/neo4j/neo4j/issues/12624).

**Comment by JoelBergstrand** [comment]
You can use [apoc.import.csv](https://neo4j.com/labs/apoc/4.1/overview/apoc.import/apoc.import.csv/) to round trip the result of apoc.export.csv.all.
