### ISSUE TITLE
Explain documentation structure in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#73]
<a href="https://github.com/fbiville"><img src="https://avatars.githubusercontent.com/u/445792?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fbiville](https://github.com/fbiville)**
_Thursday Mar 25, 2021 at 15:44 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1836_

----

Contributing to documentation is not straightforward to newcomers, since the documentation is generated **and** versioned  in Asciidoc files, but the information comes most of the time from the Java source files.

**Comment by gem-neo4j** [comment]
Documentation is no longer generated and has its own repo :) same workflow as adding to the Cypher docs; https://github.com/neo4j/docs-apoc
