### ISSUE TITLE
Document apoc.convert.toTree

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#74]
<a href="https://github.com/fbiville"><img src="https://avatars.githubusercontent.com/u/445792?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fbiville](https://github.com/fbiville)**
_Thursday Apr 15, 2021 at 14:57 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1855_

----

Currently, the structure of `apoc.convert.toTree` output is not super clear.
It would be good to add some examples.

**Comment by JoelBergstrand** [comment]
Examples now exists for both `apoc.convert.toTree` (deprecated) and `apoc.convert.toJsonTree` (replacement).
