### ISSUE TITLE
add apoc.rel.startNodeId() apoc.rel.endNodeId() for real and virtual relationships 

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#75]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Friday Dec 11, 2020 at 15:39 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1753_

----

see `apoc.rel.type()`

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/core/src/main/java/apoc/nodes/Nodes.java#L426

**Comment by JoelBergstrand** [comment]
If this is important please open a new card with more information.
