### ISSUE TITLE
parallelization for apoc.path.expand

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#83]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Wednesday Jun 03, 2020 at 10:16 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1539_

----

In general apoc.path.expand should parallelize nicely.

Either document how do do it with periodic iterate
Or add an option parallel:true that parallelizes from stepX e.g. when a good number of parallel branches is reached?

**Comment by hvub** [comment]
In general, we should rather get people to use quantified path patterns and parallel runtime.
