### ISSUE TITLE
apoc.meta.subgraph returns java.lang.NullPointerException

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#86]
<a href="https://github.com/typinator"><img src="https://avatars.githubusercontent.com/u/14157480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [typinator](https://github.com/typinator)**
_Wednesday Apr 29, 2020 at 07:36 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1491_

----

`CALL apoc.meta.subGraph({labels:["A", "B","C"],rels:[],excludes:[]})`

behaves as expected where elements with labels A, B and C exist.

If elements do not match any of the labels an error is returned:
```
Neo.ClientError.Procedure.ProcedureCallFailed

Failed to invoke procedure `apoc.meta.subGraph`: Caused by: java.lang.NullPointerException
```

which is a fault - if any or all of the labels aren't present it should return nothing for the respective label not an error.

**Comment by gem-neo4j** [comment]
Can't reproduce on any of my APOC builds, I am going to assume this has been fixed and can be reopened if it is found to be not true at some point :)
