### ISSUE TITLE
Support for Fabric - 

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#87]
<a href="https://github.com/graphadvantage"><img src="https://avatars.githubusercontent.com/u/5991751?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [graphadvantage](https://github.com/graphadvantage)**
_Saturday Aug 08, 2020 at 14:56 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1615_

----

## Feature description (Mandatory)
Apoc support for Neo4j Fabric operations, ability to directly merge virtual nodes and rels queried from Fabric shards.  Ability to create a symmetric index for semantically identical nodes across shards, and use this index to merge vNodes for downstream query operations. Merged vNodes should retain metadata on their provenance (fabric graph id and node id) to support write back to the source shard. -->  apoc.merge.vNodeFromFabricNode() ,  apoc.merge.vGraphFromFabricPaths()

## Considered alternatives
Have some workarounds using existing apoc.create.vNode and apoc.create.vRelationship, nothing elegant :(
https://community.neo4j.com/t/neo4j-fabric-sharded-subgraph-reassembly-for-advanced-querying/22731

## How this feature can improve the project?
Ability to perform downstream operations/queries with elements drawn from fabric graph shards will improve the utility and adoption of fabric and enterprise graph sharding.  Any real world implementation of fabric will necessarily involve hierarchy and other entities stored in multiple graph shards that will need virtual reassembly by the federated query to construct an accurate subgraph for downstream query operations.
https://github.com/neo4j/neo4j/issues/12563

thank you!

Michael

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jexp](https://github.com/jexp)**
_Monday Aug 10, 2020 at 10:51 GMT_

----

Can you provide a bit more detail / examples for what you want to do Michael?

**Comment by neo-technology-build-agent** [comment]
<a href="https://github.com/graphadvantage"><img src="https://avatars.githubusercontent.com/u/5991751?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [graphadvantage](https://github.com/graphadvantage)**
_Friday Oct 23, 2020 at 23:05 GMT_

----

Hi Michael - yes I'll see if I can work something up for you using example data.  The basic idea is to be able to search across fabric shards for an equivalent node, and then merge these equivalent nodes during the union step into a meaningful subgraph.  Currently equivalent nodes are treated as unrelated nodes in the union output.

**Comment by hvub** [comment]
It is not necessarily clear what "equivalent nodes" means. However, if we assume it means something stimple like "same labels and same properties", then the post processing and group the unioned result with `WITH labels(n), properties(n), COLLECT(n) AS list` (regular Cypher means) and turn the groups into a virtual node using APOC (or do whatever the use case requires).

Even equivalence notions that involve characteristics of neighboring graph element reachable with a pattern match and non-recursive can be expressed that way. 

Hence, I do not see that this needs an addition to APOC. 

If "equivalent nodes" means something more fancy with a recursive definition, e.g. node equivalent via a graph automorphism (or variants of that), than there are indeed no tools for that in Cypher or APOC. However, these is a fairly complex equivalence notions, i.e. unlike to broadly requested things.

The imprecision of what "equivalent nodes" means will make it hard anyway to add something with a broad usage.
