### ISSUE TITLE
Find better names for whitelist/blacklist in the APOC code base and docs

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#92]
<a href="https://github.com/jexp"><img src="https://avatars.githubusercontent.com/u/67427?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jexp](https://github.com/jexp)**
_Monday Jun 15, 2020 at 13:04 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1561_

----

I found the occurrences of those in the path expander functions, metadata,  and some other code pieces.

**Comment by gem-neo4j** [comment]
This was updated and the offending names deprecated :)
