### ISSUE TITLE
requested readme.adoc and on Version Compatibility point to http://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json 

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#93]
<a href="https://github.com/Dcanzano"><img src="https://avatars.githubusercontent.com/u/16004526?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Dcanzano](https://github.com/Dcanzano)**
_Thursday Jul 02, 2020 at 17:46 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1578_

----

## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Feature description (Mandatory)
requested readme.adoc and on Version Compatibility point to http://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json 

as the current refers to a apoc 3.5.0.11 when 3.5.0.12 has been released, so readme.adoc is a bit behind

## How this feature can improve the project?
update the versions.json and point everything to that... and then all is good with the world

**Comment by gem-neo4j** [comment]
README has been updated and the version matrix is also removed :)
